'use strict'


export const CREATE_SIMULATION = 'CREATE_SIMULATION'

export const CREATE_AUTHOR = 'CREATE_AUTHOR'
export const CREATE_GENERATOR = 'CREATE_GENERATOR'
export const CREATE_SUPPORTER = 'CREATE_SUPPORTER'
export const UPDATE_AUTHORS_SUPPORT_PROBABILITY = 'UPDATE_AUTHORS_SUPPORT_PROBABILITY'
export const UPDATE_POS_BLOCK_PROBABILITY = 'UPDATE_POS_BLOCK_PROBABILITY'

export const ESTABLISH_SUPPORT = 'ESTABLISH_SUPPORT';
export const UPDATE_STRUCTURE = 'UPDATE_STRUCTURE';

export const GENERATE_POS_BLOCK = 'GENERATE_POS_BLOCK'
export const RESET_STATE = 'RESET_STATE';

export const RESTART_STATE = 'RESTART';

export const CLEAR_STATISTICS = 'CLEAR_STATISTICS'
export const ADD_STATISTICS_RAW = 'ADD_STATISTICS_RAW'
export const COMPUTE_STATISTICS = 'COMPUTE_STATISTICS'

